---
markdown: kramdown
highlighter: rouge
title: Playing what's not there
tagline: ''
description: You've got to dig it to dig it, You dig?
url: https://example.com
baseurl: ''
author:
  name: Dominic A
  url: adominic022@gmail.com
paginate: 5
exclude:
- README.md
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: false
theme_colors:
  sidebar-bg-color: "#A78FA9"
  sidebar-fg-color: "#CCCCCC"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: true
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
