---
markdown: kramdown
highlighter: rouge
title: Mood Indigo
tagline: A Jekyll theme
description: You've got to dig it, You dig?
url: https://example.com
baseurl: ''
author:
  name: Dominic A
  url: ''
paginate: 5
exclude:
- README.md
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#3A595C"
  sidebar-fg-color: "#EDEEF0"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: true
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
